version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3001
    depends_on:
      - mongodb

  note-service:
    build: ./note-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3002
    depends_on:
      - mongodb

  profile-service:
    build: ./profile-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3003
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: